In [3]:
import torch
import numpy as np

In [12]:
def modified_gram_schmidt_qr(A): # 5 pts
    assert A.shape[0] >= A.shape[1], 'm is not >= n'
    new_vectors = torch.zeros(A.shape)
    for i in range(A.shape[1]):
        new_vectors[:,i] += A[:,i]
        if i > 0:
            tmp = torch.tensor(new_vectors[:,0])
            new_vectors[:,i] -= ((A[:,i] @ tmp)/(tmp @ tmp)) * tmp
        
        for j in range(1,i):
            tmp1 = torch.tensor(new_vectors[:,i])
            tmp2 = torch.tensor(new_vectors[:,j])
            new_vectors[:,i] -= ((tmp1 @ tmp2)/(tmp2 @ tmp2)) * tmp2
        
    # normalization
    for i in range(new_vectors.shape[1]):
        tmp3 = torch.tensor(new_vectors[:,i])
        new_vectors[:,i] /= torch.tensor(tmp3).norm()
    Q = new_vectors
    R = torch.zeros((A.shape[1],A.shape[1]))
    for i in range(A.shape[1]):
        for j in range(i, A.shape[1]):
            R[i,j] += A[:,j] @ new_vectors[:,i]
    return -Q, -R

In [13]:
A0 = torch.tensor([[12., -51, 4], [6, 167, -68], [-4, 24, -41]], requires_grad=True)
A1 = torch.tensor([[3., -4, 5], [2, 150, -58], [-4, 24, -31]])

In [14]:
q1, r1 = torch.qr(A0)

In [15]:
q2, r2 = modified_gram_schmidt_qr(A0)

/home/dmitriy/MyEnv/other/skoltech/ml/env/lib/python3.5/site-packages/ipykernel_launcher.py:7: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  import sys
/home/dmitriy/MyEnv/other/skoltech/ml/env/lib/python3.5/site-packages/ipykernel_launcher.py:11: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  # This is added back by InteractiveShellApp.init_path()
/home/dmitriy/MyEnv/other/skoltech/ml/env/lib/python3.5/site-packages/ipykernel_launcher.py:12: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  if sys.path[0] == '':
/home/dmitriy/MyEnv/other/skol

In [16]:
q1

tensor([[-0.8571,  0.3943,  0.3314],
        [-0.4286, -0.9029, -0.0343],
        [ 0.2857, -0.1714,  0.9429]], grad_fn=<QrBackward>)

In [17]:
q2

tensor([[-0.8571,  0.3943,  0.3314],
        [-0.4286, -0.9029, -0.0343],
        [ 0.2857, -0.1714,  0.9429]], grad_fn=<NegBackward>)

In [18]:
r1

tensor([[ -14.0000,  -21.0000,   14.0000],
        [   0.0000, -175.0000,   70.0000],
        [   0.0000,    0.0000,  -35.0000]], grad_fn=<QrBackward>)

In [19]:
r2

tensor([[ -14.0000,  -21.0000,   14.0000],
        [  -0.0000, -175.0000,   70.0000],
        [  -0.0000,   -0.0000,  -35.0000]], grad_fn=<NegBackward>)

In [11]:
(q2 @ r2).sum().backward()

In [186]:
A0.grad

tensor([[-0.1429,  1.0064,  1.8583],
        [ 9.4286,  2.0272,  4.4091],
        [-0.2857,  0.3648,  3.4526]])

In [20]:
def qralgo(a):
    while torch.sqrt(torch.sum(a.tril(-1)-1)) > 1e-9: 
        q,r = modified_gram_schmidt_qr(a) 
        a = r @ q
    return a

def eigvals(a):
    return qralgo(a).diag()

def weighted_norm(a, b):
    norm = 0.0
    
    for i in range (len (a)):
        norm += (a [i] - b [i])**2 / (i + 1)
    
    return norm

In [21]:
eigvals(A0)

/home/dmitriy/MyEnv/other/skoltech/ml/env/lib/python3.5/site-packages/ipykernel_launcher.py:7: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  import sys
/home/dmitriy/MyEnv/other/skoltech/ml/env/lib/python3.5/site-packages/ipykernel_launcher.py:11: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  # This is added back by InteractiveShellApp.init_path()
/home/dmitriy/MyEnv/other/skoltech/ml/env/lib/python3.5/site-packages/ipykernel_launcher.py:12: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  if sys.path[0] == '':
/home/dmitriy/MyEnv/other/skol

tensor([156.1257, -32.5522,  14.4264], grad_fn=<DiagBackward>)

In [22]:
eigvals(A1)

/home/dmitriy/MyEnv/other/skoltech/ml/env/lib/python3.5/site-packages/ipykernel_launcher.py:7: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  import sys
/home/dmitriy/MyEnv/other/skoltech/ml/env/lib/python3.5/site-packages/ipykernel_launcher.py:11: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  # This is added back by InteractiveShellApp.init_path()
/home/dmitriy/MyEnv/other/skoltech/ml/env/lib/python3.5/site-packages/ipykernel_launcher.py:12: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  if sys.path[0] == '':
/home/dmitriy/MyEnv/other/skol

tensor([143.9456, -24.3240,   2.3782])

In [23]:
optimizer = torch.optim.Adam([A0], lr = 0.1)
target = eigvals(A1)
print(target)

for _ in range (10000):
    
    current_eigen = eigvals(A0)
    
    #loss =   weighted_norm(current_eigen, mu)+pen# calculate loss
    loss =   weighted_norm(current_eigen, target)

    optimizer.zero_grad()  # clear previous gradients
    loss.backward()        # compute gradients of all variables wrt loss

    optimizer.step()
    if _ % 25 == 0:
        print (current_eigen)

/home/dmitriy/MyEnv/other/skoltech/ml/env/lib/python3.5/site-packages/ipykernel_launcher.py:7: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  import sys
/home/dmitriy/MyEnv/other/skoltech/ml/env/lib/python3.5/site-packages/ipykernel_launcher.py:11: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  # This is added back by InteractiveShellApp.init_path()
/home/dmitriy/MyEnv/other/skoltech/ml/env/lib/python3.5/site-packages/ipykernel_launcher.py:12: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  if sys.path[0] == '':
/home/dmitriy/MyEnv/other/skol

tensor([143.9456, -24.3240,   2.3782])
tensor([156.1257, -32.5522,  14.4264], grad_fn=<DiagBackward>)
tensor([155.9595, -33.9232,  14.6338], grad_fn=<DiagBackward>)
tensor([154.4713, -14.3851,  -6.0560], grad_fn=<DiagBackward>)
tensor([  6.0706, 149.3880, -21.3504], grad_fn=<DiagBackward>)
tensor([  9.1313, 148.5795, -22.1176], grad_fn=<DiagBackward>)
tensor([ 11.6189, 148.7974, -23.1234], grad_fn=<DiagBackward>)
tensor([ 13.9154, 148.9776, -23.8424], grad_fn=<DiagBackward>)
tensor([ 16.1161, 149.0553, -24.3382], grad_fn=<DiagBackward>)
tensor([ 18.2628, 149.0412, -24.6781], grad_fn=<DiagBackward>)
tensor([ 20.3768, 148.9494, -24.9066], grad_fn=<DiagBackward>)
tensor([ 22.4691, 148.7921, -25.0530], grad_fn=<DiagBackward>)
tensor([ 24.5457, 148.5785, -25.1371], grad_fn=<DiagBackward>)
tensor([ 26.6093, 148.3160, -25.1724], grad_fn=<DiagBackward>)
tensor([ 28.6612, 148.0107, -25.1686], grad_fn=<DiagBackward>)
tensor([ 30.7019, 147.6671, -25.1329], grad_fn=<DiagBackward>)
tensor([ 32.7313

tensor([143.1623,  51.4435,  -1.0312], grad_fn=<DiagBackward>)
tensor([143.2254,  50.7386,  -1.0352], grad_fn=<DiagBackward>)
tensor([143.2843,  50.0283,  -1.0352], grad_fn=<DiagBackward>)
tensor([143.3390,  49.3137,  -1.0312], grad_fn=<DiagBackward>)
tensor([143.3898,  48.5959,  -1.0242], grad_fn=<DiagBackward>)
tensor([143.4370,  47.8759,  -1.0142], grad_fn=<DiagBackward>)
tensor([143.4808,  47.1549,  -1.0016], grad_fn=<DiagBackward>)
tensor([143.5212,  46.4338,  -0.9867], grad_fn=<DiagBackward>)
tensor([143.5587,  45.7137,  -0.9704], grad_fn=<DiagBackward>)
tensor([143.5933,  44.9954,  -0.9527], grad_fn=<DiagBackward>)
tensor([143.6252,  44.2797,  -0.9345], grad_fn=<DiagBackward>)
tensor([143.6546,  43.5674,  -0.9158], grad_fn=<DiagBackward>)
tensor([143.6817,  42.8590,  -0.8974], grad_fn=<DiagBackward>)
tensor([143.7066,  42.1548,  -0.8794], grad_fn=<DiagBackward>)
tensor([143.7294,  41.4553,  -0.8624], grad_fn=<DiagBackward>)
tensor([143.7503,  40.7604,  -0.8468], grad_fn=<DiagBac

tensor([143.9444, -11.7137,   0.5621], grad_fn=<DiagBackward>)
tensor([143.9444, -12.0204,   0.6141], grad_fn=<DiagBackward>)
tensor([143.9444, -12.3235,   0.6652], grad_fn=<DiagBackward>)
tensor([143.9444, -12.6227,   0.7155], grad_fn=<DiagBackward>)
tensor([143.9444, -12.9180,   0.7649], grad_fn=<DiagBackward>)
tensor([143.9444, -13.2095,   0.8135], grad_fn=<DiagBackward>)
tensor([143.9445, -13.4970,   0.8612], grad_fn=<DiagBackward>)
tensor([143.9445, -13.7806,   0.9080], grad_fn=<DiagBackward>)
tensor([143.9445, -14.0602,   0.9539], grad_fn=<DiagBackward>)
tensor([143.9445, -14.3357,   0.9990], grad_fn=<DiagBackward>)
tensor([143.9445, -14.6072,   1.0431], grad_fn=<DiagBackward>)
tensor([143.9445, -14.8746,   1.0864], grad_fn=<DiagBackward>)
tensor([143.9445, -15.1378,   1.1289], grad_fn=<DiagBackward>)
tensor([143.9446, -15.3969,   1.1704], grad_fn=<DiagBackward>)
tensor([143.9446, -15.6518,   1.2111], grad_fn=<DiagBackward>)
tensor([143.9446, -15.9025,   1.2509], grad_fn=<DiagBac

In [4]:
torch.eye(A0.shape[0])

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [6]:
np.min((1,2))

1

In [10]:
np.linalg.norm([1.0,2.0,3.0])

3.7416573867739413

In [13]:
torch.tensor([1.0,2.0,3.0], requires_grad=True).norm().backward()